# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common.proto',
  package='bluetooth.facade',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/common.proto\x12\x10\x62luetooth.facade\"\x07\n\x05\x45mpty\"\x17\n\x04\x44\x61ta\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"#\n\x10\x42luetoothAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\"\x89\x01\n\x18\x42luetoothAddressWithType\x12\x33\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\".bluetooth.facade.BluetoothAddress\x12\x38\n\x04type\x18\x02 \x01(\x0e\x32*.bluetooth.facade.BluetoothAddressTypeEnum*\x8a\x01\n\x18\x42luetoothAddressTypeEnum\x12\x19\n\x15PUBLIC_DEVICE_ADDRESS\x10\x00\x12\x19\n\x15RANDOM_DEVICE_ADDRESS\x10\x01\x12\x1b\n\x17PUBLIC_IDENTITY_ADDRESS\x10\x02\x12\x1b\n\x17RANDOM_IDENTITY_ADDRESS\x10\x03*\x9f\x01\n\x1b\x42luetoothOwnAddressTypeEnum\x12\x1d\n\x19USE_PUBLIC_DEVICE_ADDRESS\x10\x00\x12\x1d\n\x19USE_RANDOM_DEVICE_ADDRESS\x10\x01\x12 \n\x1cRESOLVABLE_OR_PUBLIC_ADDRESS\x10\x02\x12 \n\x1cRESOLVABLE_OR_RANDOM_ADDRESS\x10\x03*l\n\x1c\x42luetoothPeerAddressTypeEnum\x12%\n!PUBLIC_DEVICE_OR_IDENTITY_ADDRESS\x10\x00\x12%\n!RANDOM_DEVICE_OR_IDENTITY_ADDRESS\x10\x01\x62\x06proto3'
)

_BLUETOOTHADDRESSTYPEENUM = _descriptor.EnumDescriptor(
  name='BluetoothAddressTypeEnum',
  full_name='bluetooth.facade.BluetoothAddressTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PUBLIC_DEVICE_ADDRESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RANDOM_DEVICE_ADDRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC_IDENTITY_ADDRESS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RANDOM_IDENTITY_ADDRESS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=252,
  serialized_end=390,
)
_sym_db.RegisterEnumDescriptor(_BLUETOOTHADDRESSTYPEENUM)

BluetoothAddressTypeEnum = enum_type_wrapper.EnumTypeWrapper(_BLUETOOTHADDRESSTYPEENUM)
_BLUETOOTHOWNADDRESSTYPEENUM = _descriptor.EnumDescriptor(
  name='BluetoothOwnAddressTypeEnum',
  full_name='bluetooth.facade.BluetoothOwnAddressTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USE_PUBLIC_DEVICE_ADDRESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USE_RANDOM_DEVICE_ADDRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESOLVABLE_OR_PUBLIC_ADDRESS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESOLVABLE_OR_RANDOM_ADDRESS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=393,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_BLUETOOTHOWNADDRESSTYPEENUM)

BluetoothOwnAddressTypeEnum = enum_type_wrapper.EnumTypeWrapper(_BLUETOOTHOWNADDRESSTYPEENUM)
_BLUETOOTHPEERADDRESSTYPEENUM = _descriptor.EnumDescriptor(
  name='BluetoothPeerAddressTypeEnum',
  full_name='bluetooth.facade.BluetoothPeerAddressTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PUBLIC_DEVICE_OR_IDENTITY_ADDRESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RANDOM_DEVICE_OR_IDENTITY_ADDRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=554,
  serialized_end=662,
)
_sym_db.RegisterEnumDescriptor(_BLUETOOTHPEERADDRESSTYPEENUM)

BluetoothPeerAddressTypeEnum = enum_type_wrapper.EnumTypeWrapper(_BLUETOOTHPEERADDRESSTYPEENUM)
PUBLIC_DEVICE_ADDRESS = 0
RANDOM_DEVICE_ADDRESS = 1
PUBLIC_IDENTITY_ADDRESS = 2
RANDOM_IDENTITY_ADDRESS = 3
USE_PUBLIC_DEVICE_ADDRESS = 0
USE_RANDOM_DEVICE_ADDRESS = 1
RESOLVABLE_OR_PUBLIC_ADDRESS = 2
RESOLVABLE_OR_RANDOM_ADDRESS = 3
PUBLIC_DEVICE_OR_IDENTITY_ADDRESS = 0
RANDOM_DEVICE_OR_IDENTITY_ADDRESS = 1



_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='bluetooth.facade.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=47,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='bluetooth.facade.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='bluetooth.facade.Data.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=72,
)


_BLUETOOTHADDRESS = _descriptor.Descriptor(
  name='BluetoothAddress',
  full_name='bluetooth.facade.BluetoothAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='bluetooth.facade.BluetoothAddress.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)


_BLUETOOTHADDRESSWITHTYPE = _descriptor.Descriptor(
  name='BluetoothAddressWithType',
  full_name='bluetooth.facade.BluetoothAddressWithType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='bluetooth.facade.BluetoothAddressWithType.address', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='bluetooth.facade.BluetoothAddressWithType.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=249,
)

_BLUETOOTHADDRESSWITHTYPE.fields_by_name['address'].message_type = _BLUETOOTHADDRESS
_BLUETOOTHADDRESSWITHTYPE.fields_by_name['type'].enum_type = _BLUETOOTHADDRESSTYPEENUM
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['BluetoothAddress'] = _BLUETOOTHADDRESS
DESCRIPTOR.message_types_by_name['BluetoothAddressWithType'] = _BLUETOOTHADDRESSWITHTYPE
DESCRIPTOR.enum_types_by_name['BluetoothAddressTypeEnum'] = _BLUETOOTHADDRESSTYPEENUM
DESCRIPTOR.enum_types_by_name['BluetoothOwnAddressTypeEnum'] = _BLUETOOTHOWNADDRESSTYPEENUM
DESCRIPTOR.enum_types_by_name['BluetoothPeerAddressTypeEnum'] = _BLUETOOTHPEERADDRESSTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.facade.Empty)
  })
_sym_db.RegisterMessage(Empty)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.facade.Data)
  })
_sym_db.RegisterMessage(Data)

BluetoothAddress = _reflection.GeneratedProtocolMessageType('BluetoothAddress', (_message.Message,), {
  'DESCRIPTOR' : _BLUETOOTHADDRESS,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.facade.BluetoothAddress)
  })
_sym_db.RegisterMessage(BluetoothAddress)

BluetoothAddressWithType = _reflection.GeneratedProtocolMessageType('BluetoothAddressWithType', (_message.Message,), {
  'DESCRIPTOR' : _BLUETOOTHADDRESSWITHTYPE,
  '__module__' : 'proto.common_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.facade.BluetoothAddressWithType)
  })
_sym_db.RegisterMessage(BluetoothAddressWithType)


# @@protoc_insertion_point(module_scope)
