# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/neighbor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/neighbor.proto',
  package='bluetooth.neighbor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14proto/neighbor.proto\x12\x12\x62luetooth.neighbor\x1a\x12proto/common.proto\"\x1c\n\tEnableMsg\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"L\n\x13\x44iscoverabilitiyMsg\x12\x35\n\x04mode\x18\x01 \x01(\x0e\x32\'.bluetooth.neighbor.DiscoverabilityMode\"\xab\x01\n\nInquiryMsg\x12=\n\x0cinquiry_mode\x18\x01 \x01(\x0e\x32\'.bluetooth.neighbor.DiscoverabilityMode\x12\x33\n\x0bresult_mode\x18\x02 \x01(\x0e\x32\x1e.bluetooth.neighbor.ResultMode\x12\x14\n\x0clength_1_28s\x18\x03 \x01(\r\x12\x13\n\x0bmax_results\x18\x04 \x01(\r\"\"\n\x10InquiryResultMsg\x12\x0e\n\x06packet\x18\x01 \x01(\x0c\"`\n\x14RemoteNameRequestMsg\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12!\n\x19page_scan_repetition_mode\x18\x02 \x01(\r\x12\x14\n\x0c\x63lock_offset\x18\x03 \x01(\r\"F\n\x15RemoteNameResponseMsg\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0c\x12\x0c\n\x04name\x18\x03 \x01(\x0c*8\n\x13\x44iscoverabilityMode\x12\x07\n\x03OFF\x10\x00\x12\x0b\n\x07LIMITED\x10\x01\x12\x0b\n\x07GENERAL\x10\x02*2\n\nResultMode\x12\x0c\n\x08STANDARD\x10\x00\x12\x08\n\x04RSSI\x10\x01\x12\x0c\n\x08\x45XTENDED\x10\x02\x32\xe6\x04\n\x0eNeighborFacade\x12M\n\x11SetConnectability\x12\x1d.bluetooth.neighbor.EnableMsg\x1a\x17.bluetooth.facade.Empty\"\x00\x12X\n\x12SetDiscoverability\x12\'.bluetooth.neighbor.DiscoverabilitiyMsg\x1a\x17.bluetooth.facade.Empty\"\x00\x12Z\n\x0eSetInquiryMode\x12\x1e.bluetooth.neighbor.InquiryMsg\x1a$.bluetooth.neighbor.InquiryResultMsg\"\x00\x30\x01\x12U\n\x0eReadRemoteName\x12(.bluetooth.neighbor.RemoteNameRequestMsg\x1a\x17.bluetooth.facade.Empty\"\x00\x12]\n\x13GetRemoteNameEvents\x12\x17.bluetooth.facade.Empty\x1a).bluetooth.neighbor.RemoteNameResponseMsg\"\x00\x30\x01\x12M\n\x11\x45nableInquiryScan\x12\x1d.bluetooth.neighbor.EnableMsg\x1a\x17.bluetooth.facade.Empty\"\x00\x12J\n\x0e\x45nablePageScan\x12\x1d.bluetooth.neighbor.EnableMsg\x1a\x17.bluetooth.facade.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[proto_dot_common__pb2.DESCRIPTOR,])

_DISCOVERABILITYMODE = _descriptor.EnumDescriptor(
  name='DiscoverabilityMode',
  full_name='bluetooth.neighbor.DiscoverabilityMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIMITED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GENERAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=552,
  serialized_end=608,
)
_sym_db.RegisterEnumDescriptor(_DISCOVERABILITYMODE)

DiscoverabilityMode = enum_type_wrapper.EnumTypeWrapper(_DISCOVERABILITYMODE)
_RESULTMODE = _descriptor.EnumDescriptor(
  name='ResultMode',
  full_name='bluetooth.neighbor.ResultMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STANDARD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RSSI', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTENDED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=610,
  serialized_end=660,
)
_sym_db.RegisterEnumDescriptor(_RESULTMODE)

ResultMode = enum_type_wrapper.EnumTypeWrapper(_RESULTMODE)
OFF = 0
LIMITED = 1
GENERAL = 2
STANDARD = 0
RSSI = 1
EXTENDED = 2



_ENABLEMSG = _descriptor.Descriptor(
  name='EnableMsg',
  full_name='bluetooth.neighbor.EnableMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='bluetooth.neighbor.EnableMsg.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=92,
)


_DISCOVERABILITIYMSG = _descriptor.Descriptor(
  name='DiscoverabilitiyMsg',
  full_name='bluetooth.neighbor.DiscoverabilitiyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='bluetooth.neighbor.DiscoverabilitiyMsg.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=170,
)


_INQUIRYMSG = _descriptor.Descriptor(
  name='InquiryMsg',
  full_name='bluetooth.neighbor.InquiryMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inquiry_mode', full_name='bluetooth.neighbor.InquiryMsg.inquiry_mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_mode', full_name='bluetooth.neighbor.InquiryMsg.result_mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length_1_28s', full_name='bluetooth.neighbor.InquiryMsg.length_1_28s', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_results', full_name='bluetooth.neighbor.InquiryMsg.max_results', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=344,
)


_INQUIRYRESULTMSG = _descriptor.Descriptor(
  name='InquiryResultMsg',
  full_name='bluetooth.neighbor.InquiryResultMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='bluetooth.neighbor.InquiryResultMsg.packet', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=380,
)


_REMOTENAMEREQUESTMSG = _descriptor.Descriptor(
  name='RemoteNameRequestMsg',
  full_name='bluetooth.neighbor.RemoteNameRequestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='bluetooth.neighbor.RemoteNameRequestMsg.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_scan_repetition_mode', full_name='bluetooth.neighbor.RemoteNameRequestMsg.page_scan_repetition_mode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock_offset', full_name='bluetooth.neighbor.RemoteNameRequestMsg.clock_offset', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=478,
)


_REMOTENAMERESPONSEMSG = _descriptor.Descriptor(
  name='RemoteNameResponseMsg',
  full_name='bluetooth.neighbor.RemoteNameResponseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='bluetooth.neighbor.RemoteNameResponseMsg.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='bluetooth.neighbor.RemoteNameResponseMsg.address', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='bluetooth.neighbor.RemoteNameResponseMsg.name', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=550,
)

_DISCOVERABILITIYMSG.fields_by_name['mode'].enum_type = _DISCOVERABILITYMODE
_INQUIRYMSG.fields_by_name['inquiry_mode'].enum_type = _DISCOVERABILITYMODE
_INQUIRYMSG.fields_by_name['result_mode'].enum_type = _RESULTMODE
DESCRIPTOR.message_types_by_name['EnableMsg'] = _ENABLEMSG
DESCRIPTOR.message_types_by_name['DiscoverabilitiyMsg'] = _DISCOVERABILITIYMSG
DESCRIPTOR.message_types_by_name['InquiryMsg'] = _INQUIRYMSG
DESCRIPTOR.message_types_by_name['InquiryResultMsg'] = _INQUIRYRESULTMSG
DESCRIPTOR.message_types_by_name['RemoteNameRequestMsg'] = _REMOTENAMEREQUESTMSG
DESCRIPTOR.message_types_by_name['RemoteNameResponseMsg'] = _REMOTENAMERESPONSEMSG
DESCRIPTOR.enum_types_by_name['DiscoverabilityMode'] = _DISCOVERABILITYMODE
DESCRIPTOR.enum_types_by_name['ResultMode'] = _RESULTMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnableMsg = _reflection.GeneratedProtocolMessageType('EnableMsg', (_message.Message,), {
  'DESCRIPTOR' : _ENABLEMSG,
  '__module__' : 'proto.neighbor_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.neighbor.EnableMsg)
  })
_sym_db.RegisterMessage(EnableMsg)

DiscoverabilitiyMsg = _reflection.GeneratedProtocolMessageType('DiscoverabilitiyMsg', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERABILITIYMSG,
  '__module__' : 'proto.neighbor_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.neighbor.DiscoverabilitiyMsg)
  })
_sym_db.RegisterMessage(DiscoverabilitiyMsg)

InquiryMsg = _reflection.GeneratedProtocolMessageType('InquiryMsg', (_message.Message,), {
  'DESCRIPTOR' : _INQUIRYMSG,
  '__module__' : 'proto.neighbor_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.neighbor.InquiryMsg)
  })
_sym_db.RegisterMessage(InquiryMsg)

InquiryResultMsg = _reflection.GeneratedProtocolMessageType('InquiryResultMsg', (_message.Message,), {
  'DESCRIPTOR' : _INQUIRYRESULTMSG,
  '__module__' : 'proto.neighbor_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.neighbor.InquiryResultMsg)
  })
_sym_db.RegisterMessage(InquiryResultMsg)

RemoteNameRequestMsg = _reflection.GeneratedProtocolMessageType('RemoteNameRequestMsg', (_message.Message,), {
  'DESCRIPTOR' : _REMOTENAMEREQUESTMSG,
  '__module__' : 'proto.neighbor_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.neighbor.RemoteNameRequestMsg)
  })
_sym_db.RegisterMessage(RemoteNameRequestMsg)

RemoteNameResponseMsg = _reflection.GeneratedProtocolMessageType('RemoteNameResponseMsg', (_message.Message,), {
  'DESCRIPTOR' : _REMOTENAMERESPONSEMSG,
  '__module__' : 'proto.neighbor_pb2'
  # @@protoc_insertion_point(class_scope:bluetooth.neighbor.RemoteNameResponseMsg)
  })
_sym_db.RegisterMessage(RemoteNameResponseMsg)



_NEIGHBORFACADE = _descriptor.ServiceDescriptor(
  name='NeighborFacade',
  full_name='bluetooth.neighbor.NeighborFacade',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=663,
  serialized_end=1277,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetConnectability',
    full_name='bluetooth.neighbor.NeighborFacade.SetConnectability',
    index=0,
    containing_service=None,
    input_type=_ENABLEMSG,
    output_type=proto_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetDiscoverability',
    full_name='bluetooth.neighbor.NeighborFacade.SetDiscoverability',
    index=1,
    containing_service=None,
    input_type=_DISCOVERABILITIYMSG,
    output_type=proto_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInquiryMode',
    full_name='bluetooth.neighbor.NeighborFacade.SetInquiryMode',
    index=2,
    containing_service=None,
    input_type=_INQUIRYMSG,
    output_type=_INQUIRYRESULTMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadRemoteName',
    full_name='bluetooth.neighbor.NeighborFacade.ReadRemoteName',
    index=3,
    containing_service=None,
    input_type=_REMOTENAMEREQUESTMSG,
    output_type=proto_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRemoteNameEvents',
    full_name='bluetooth.neighbor.NeighborFacade.GetRemoteNameEvents',
    index=4,
    containing_service=None,
    input_type=proto_dot_common__pb2._EMPTY,
    output_type=_REMOTENAMERESPONSEMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EnableInquiryScan',
    full_name='bluetooth.neighbor.NeighborFacade.EnableInquiryScan',
    index=5,
    containing_service=None,
    input_type=_ENABLEMSG,
    output_type=proto_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EnablePageScan',
    full_name='bluetooth.neighbor.NeighborFacade.EnablePageScan',
    index=6,
    containing_service=None,
    input_type=_ENABLEMSG,
    output_type=proto_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEIGHBORFACADE)

DESCRIPTOR.services_by_name['NeighborFacade'] = _NEIGHBORFACADE

# @@protoc_insertion_point(module_scope)
