# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import common_pb2 as proto_dot_common__pb2
from . import rootservice_pb2 as proto_dot_rootservice__pb2


class RootFacadeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartStack = channel.unary_unary(
                '/bluetooth.facade.RootFacade/StartStack',
                request_serializer=proto_dot_rootservice__pb2.StartStackRequest.SerializeToString,
                response_deserializer=proto_dot_rootservice__pb2.StartStackResponse.FromString,
                )
        self.StopStack = channel.unary_unary(
                '/bluetooth.facade.RootFacade/StopStack',
                request_serializer=proto_dot_rootservice__pb2.StopStackRequest.SerializeToString,
                response_deserializer=proto_dot_rootservice__pb2.StopStackResponse.FromString,
                )


class RootFacadeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RootFacadeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartStack': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStack,
                    request_deserializer=proto_dot_rootservice__pb2.StartStackRequest.FromString,
                    response_serializer=proto_dot_rootservice__pb2.StartStackResponse.SerializeToString,
            ),
            'StopStack': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStack,
                    request_deserializer=proto_dot_rootservice__pb2.StopStackRequest.FromString,
                    response_serializer=proto_dot_rootservice__pb2.StopStackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bluetooth.facade.RootFacade', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RootFacade(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bluetooth.facade.RootFacade/StartStack',
            proto_dot_rootservice__pb2.StartStackRequest.SerializeToString,
            proto_dot_rootservice__pb2.StartStackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bluetooth.facade.RootFacade/StopStack',
            proto_dot_rootservice__pb2.StopStackRequest.SerializeToString,
            proto_dot_rootservice__pb2.StopStackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ReadOnlyPropertyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadLocalAddress = channel.unary_unary(
                '/bluetooth.facade.ReadOnlyProperty/ReadLocalAddress',
                request_serializer=proto_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_common__pb2.BluetoothAddress.FromString,
                )


class ReadOnlyPropertyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadLocalAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReadOnlyPropertyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadLocalAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLocalAddress,
                    request_deserializer=proto_dot_common__pb2.Empty.FromString,
                    response_serializer=proto_dot_common__pb2.BluetoothAddress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bluetooth.facade.ReadOnlyProperty', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReadOnlyProperty(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadLocalAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bluetooth.facade.ReadOnlyProperty/ReadLocalAddress',
            proto_dot_common__pb2.Empty.SerializeToString,
            proto_dot_common__pb2.BluetoothAddress.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
